#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  flyway:
#    enabled: true
#
#info:
#  version: @project.version@
#  app:
#    url: localhost:8081
#
#management:
#  endpoint:
#    logfile:
#      external-file: /${user.home}/${spring.application.name}.log
#
#logging:
#  file:
#    name: /${user.home}/${spring.application.name}.log
#server:
#  port: 8084
#
## configs do eureka server
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    hostname: localhost
#    appname: pocmultitenantperdatabaseandschema
#
#oauth:
#  endpoints:
#    tokens: http://localhost:8080/auth-engine/tokens
#  token: http://localhost:8080/auth-engine/oauth/token
#  clientId: pocmultitenantperdatabaseandschema
#  clientSecret: browser
#
