spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 10
    username: central
    password: central
    port-number: 5433

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.web.client: INFO
    org.springframework.context.support: INFO
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN